import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    shell: 'src/shell/index.ts',
    resource: 'src/resource/index.ts',
    table: 'src/table/index.ts',
    form: 'src/form/index.ts',
    action: 'src/action/index.ts',
    auth: 'src/auth/index.ts',
    flash: 'src/flash/index.ts',
    utility: 'src/utility/index.ts',
    utils: 'src/utils/index.ts',
    pages: 'src/pages/index.ts',
    palette: 'src/palette/index.ts',
    widgets: 'src/widgets/index.ts',
    primitives: 'src/primitives/index.ts',
  },
  tsconfig: 'tsconfig.json',
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: false,
  minify: false,
  external: [
    'react',
    'react-dom',
    '@inertiajs/react',
    '@arqel-dev/react',
    '@arqel-dev/hooks',
    '@arqel-dev/types',
    'radix-ui',
    '@tanstack/react-table',
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
    'lucide-react',
  ],
});
