import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    register: 'src/register.ts',
    'rich-text': 'src/rich-text/index.ts',
    markdown: 'src/markdown/index.ts',
    code: 'src/code/index.ts',
    repeater: 'src/repeater/index.ts',
    builder: 'src/builder/index.ts',
    'key-value': 'src/key-value/index.ts',
    tags: 'src/tags/index.ts',
    wizard: 'src/wizard/index.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: false,
  minify: false,
  external: [
    'react',
    'react-dom',
    '@arqel-dev/ui',
    '@arqel-dev/types',
    '@inertiajs/react',
    '@tiptap/react',
    '@tiptap/starter-kit',
    '@tiptap/extension-link',
    '@tiptap/extension-image',
    '@tiptap/extension-placeholder',
    '@tiptap/extension-character-count',
    '@tiptap/core',
    '@tiptap/pm',
    '@dnd-kit/core',
    '@dnd-kit/sortable',
    '@dnd-kit/utilities',
    'shiki',
  ],
});
